version: '3'
services:
  eureka-server:
    image: eureka-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    restart: always
  gateway-proxy:
    image: gateway-proxy:0.0.1-SNAPSHOT
    volumes:
      - ./config-data:/var/config-data
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka-discovery:8761/eureka
    depends_on:
      - eureka-server
    ports:
      - 8888:8888
  inventory-service:
    image: inventory-service:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka-discovery:8761/eureka
    restart: always
    depends_on:
      - eureka-server
      - gateway-proxy
    ports:
      - 8082:8082
  store-app-ui:
    image: store-app-ui:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka-discovery:8761/eureka
    restart: on-failure
    depends_on:
      - eureka-server
      - gateway-proxy
    ports:
      - 8181:80

networks:
  default:
    external:
      name: microblink
