apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway-app
  labels:
    app: cloud-gateway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-gateway-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cloud-gateway-app
    spec:
      containers:
        - image: sedokray/gateway-proxy:0.0.1-SNAPSHOT
          name: gateway-proxy
          ports:
            - containerPort: 8700
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_service_address
      initContainers:
        - name: init-eureka-lb
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup eureka-lb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo en attente de eureka-lb; sleep 2; done"]
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-svc
  labels:
    app: cloud-gateway-app
spec:
  selector:
    app: cloud-gateway-app
  type: LoadBalancer
  ports:
    - port: 8700
      targetPort: 8700
      protocol: TCP