apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-app
  labels:
    app: config-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: config-server-app
    spec:
      containers:
        - image: config-server:0.0.1-SNAPSHOT
          name: config-server
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: config-server-svc
  labels:
    app: config-server-app
spec:
  selector:
    app: config-server-app
  type: clusterIP
  ports:
    - port: 8761
      targetPort: 8761