apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-app
  labels:
    app: config-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: config-server-app
    spec:
      containers:
        - image: config-server:0.0.1-SNAPSHOT
          name: config-server
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: config-server-svc
  labels:
    app: config-server-app
spec:
  selector:
    app: config-server-app
  type: ClusterIP # by ClusterIP , otherwase NodePort, LoadBalancer, ExternalName
  ports:
    - port: 8761
      targetPort: 8761

# ClusterIP: Expose le service sur une IP interne au cluster. Le choix de cette valeur rend le service uniquement accessible à partir du cluster. Il s'agit du ServiceType par défaut.
# NodePort: Expose le service sur l'IP de chaque nœud sur un port statique (le NodePort). Un service ClusterIP, vers lequel le service NodePort est automatiquement créé. Vous pourrez contacter le service NodePort, depuis l'extérieur du cluster, en demandant <NodeIP>: <NodePort>.
# LoadBalancer: Expose le service en externe à l'aide de l'équilibreur de charge d'un fournisseur de cloud. Les services NodePort et ClusterIP, vers lesquels les itinéraires de l'équilibreur de charge externe, sont automatiquement créés.
# ExternalName : Mappe le service au contenu du champ externalName (par exemple foo.bar.example.com), en renvoyant un enregistrement CNAME avec sa valeur. Aucun proxy d'aucune sorte n'est mis en place.