apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: wordpress-ingress
spec:
  rules:
    - host: 'test.hub'
      http:
        paths:
          - path: /
            backend:
              serviceName: frontend-store-app
              servicePort: 80