apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: storeapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: 'web.store.kub'
      http:
        paths:
          - path: /
            backend:
              service:
                name: store-app-ui-svc
                port:
                  number: 8081