apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-app-ui-app
  labels:
    app: store-app-ui-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-app-ui-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: store-app-ui-app
    spec:
      containers:
        - image: store-app-ui:0.0.1-SNAPSHOT
          name: store-app-ui
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: store-app-ui-svc
  labels:
    app: store-app-ui-app
spec:
  selector:
    app: store-app-ui-app
  type: clusterIP
  ports:
    - port: 8081
      targetPort: 80