apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-app-ui-app
  labels:
    app: store-app-ui-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-app-ui-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: store-app-ui-app
    spec:
      containers:
        - image: sedokray/store-app-ui:0.0.1-SNAPSHOT
          name: store-app-ui
          ports:
            - containerPort: 80
      initContainers: # waiting to initialise other service before creating pod
        - name: init-cloud-gateway-svc
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup cloud-gateway-svc.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo en attente de cloud-gateway-svc; sleep 2; done"]
---
apiVersion: v1
kind: Service
metadata:
  name: store-app-ui-svc
  labels:
    app: store-app-ui-app
spec:
  selector:
    app: store-app-ui-app
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 80  #  equivalent à  - containerPort: 80 dans le pod or deployement

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: storeapp-ingress
# annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /store
            pathType: Prefix
            backend:
              service:
                name: store-app-ui-svc
                port:
                  number: 8081
#    - host: 'web.store.kub'
#      http:
#       paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: store-app-ui-svc
#                port:
#                  number: 8081