server:
  port: 8081
spring:
  application:
    name: inventory-service
  cloud:
    discovery:
      enabled: true
  datasource:
    url: jdbc:h2:mem:inventory-db
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: *
allowed:
  originpattern: *